# Generated by Django 3.2.9 on 2022-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='barcode',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
